fix display of href
Assault-Lily/Lemonade pull request #266
Opened 2022-04-22 07:57 UTC by fvh-P

一部の項目だけリンクの表示が `display: block` になっていてリンク領域が行いっぱいに伸びてしまっているので修正します。

※修正前はこうなっていました。このタイプのリンクで空白領域までリンクになっているのは良くないと思います。
![無題](https://user-images.githubusercontent.com/8458066/164643940-c375a4c5-fe43-4c7a-b1fd-2c5db00156cb.png)

2022-04-22 08:47 UTC, miyacorata requested changes
`display: block;` にしてるの流石にズボラすぎるだろと反省しています...

これらは日葵隊長など過去所属していたレギオン等が複数ある場合に改行がされず見づらくなるのを回避する意図で `display: block;` にしたものです。

代替としてリンク要素を `<div>` で囲みたいと思います。

2022-04-22 08:47 UTC, miyacorata commented on resources/views/lily/show.blade.php
> +                                    <a href="{{ route('legion.show',['legion' => str_replace('lilyrdf:','',$taskforce)]) }}">
```suggestion
                                    <div><a href="{{ route('legion.show',['legion' => str_replace('lilyrdf:','',$taskforce)]) }}"></div>
```

2022-04-22 08:47 UTC, miyacorata commented on resources/views/lily/show.blade.php
> +                                    <a href="{{ route('legion.show',['legion' => str_replace('lilyrdf:','',$past_taskforce)]) }}">
```suggestion
                                    <div><a href="{{ route('legion.show',['legion' => str_replace('lilyrdf:','',$past_taskforce)]) }}"></div>
```

2022-04-22 08:47 UTC, miyacorata commented on resources/views/lily/show.blade.php
> +                                    <a href="{{ route('legion.show',['legion' => str_replace('lilyrdf:','',$past_legion)]) }}">
```suggestion
                                    <div><a href="{{ route('legion.show',['legion' => str_replace('lilyrdf:','',$past_legion)]) }}"></div>
```

2022-04-22 08:55 UTC, fvh-P commented
@miyacorata 
修正しました。

2022-04-26 02:27 UTC, miyacorata approved these changes
ありがとうございます！

2022-04-26 02:27 UTC, merged