リリィ一覧に誕生日の近い順のソートを実装
Assault-Lily/Lemonade pull request #374
Opened 2023-02-28 03:58 UTC by fvh-P

標題の通りです。
ソートオプションも一部修正しています。
![image](https://user-images.githubusercontent.com/8458066/221749917-4e447365-a7c2-44c3-9cc8-81a79af16a6c.png)

2023-03-12 18:38 UTC, miyacorata requested changes
13日確認時点で14日に誕生日を迎える人物のデータが先頭に来ない状況を確認しました。

詳しい検証と修正が必要ですのでひとまず取り込みは見送ります。

2023-03-13 04:06 UTC, fvh-P reviewed
@miyacorata 
バグの原因を解明して修正しました。🙇‍♂️

2023-03-13 04:06 UTC, fvh-P commented on app/Http/Controllers/LilyController.php
> +            $lily_sortKeyForKeyUnknown[] = isset($lily[$sort][0]) ? 0 : 1;
`!empty()` の引数に数値の `0` が入ることによって、誕生日当日のリリィが「誕生日が未定義なリリィ」として扱われてしまうことがバグの原因でした。

2023-03-13 04:06 UTC, fvh-P commented on app/Http/Controllers/LilyController.php
> +            $lily_sortKeyForKanaUnknown[] = isset($lily['lily:nameKana'][0]) ? 0 : 1;
上に合わせて変えました。

2023-03-13 04:06 UTC, fvh-P commented on app/Http/Controllers/LilyController.php
> +                        $birthday = Carbon::createFromFormat('Y--m-d', $today->year.$lily['schema:birthDate'][0])->startOfDay();
`Carbon::createFromFormat()` は時刻を指定しない場合呼び出した時刻が入るらしいので、0時ちょうどが固定で入るように `->startOfDay()` を呼んでおき、比較対象も `Carbon::now()` から `Carbon::today()` に変更しました。

2023-03-13 15:00 UTC, miyacorata approved these changes
ありがとうございます！

2023-03-13 15:00 UTC, merged